data:
  ppg_file: "../../data/mesa_ppg_with_labels.h5"
  ecg_file: "../../data/mesa_generated_ecg.h5"
  index_file: "../../data/mesa_subject_index.h5"
  num_workers: 4

training:
  batch_size: 2
  num_epochs: 50
  learning_rate: 0.0001
  weight_decay: 0.00001
  patience: 15

model:
  d_model: 256
  n_heads: 8
  n_fusion_blocks: 3
  dropout: 0.1

output:
  save_dir: "./outputs"
  save_frequency: 5


use_amp: true

model_type: "generated_ecg"